/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HelloWorld */

#ifndef _Included_HelloWorld
#define _Included_HelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     HelloWorld
 * Method:    showMessage
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_HelloWorld_showMessage
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
